Update entrypoint logging

diff --git a/docker-entrypoint b/docker-entrypoint
--- a/docker-entrypoint
+++ b/docker-entrypoint
@@ -37,6 +37,11 @@ echo AUTOHEAL_INTERVAL=${AUTOHEAL_INTERVAL}
 echo AUTOHEAL_DEFAULT_STOP_TIMEOUT=${AUTOHEAL_DEFAULT_STOP_TIMEOUT}
 echo AUTOHEAL_ONLY_MONITOR_RUNNING=${AUTOHEAL_ONLY_MONITOR_RUNNING}
 
+log_message() {
+  local message=$1
+  echo "[$(date +%Y-%m-%d" "%H:%M:%S)] $message"
+}
+
 docker_curl() {
   curl --max-time "${CURL_TIMEOUT}" --no-buffer -s \
   ${CA} ${CLIENT_KEY} ${CLIENT_CERT} \
@@ -127,21 +132,25 @@ term_handler() {
 # shellcheck disable=2039
 trap 'kill $$; term_handler' SIGTERM
 
+log_message "Docker Socket: $DOCKER_SOCK"
+log_message "HTTP Endpoint: $HTTP_ENDPOINT"
+
 if [ "$1" = "autoheal" ]
 then
   if [ -n "$UNIX_SOCK" ] && ! [ -S "$DOCKER_SOCK" ]
   then
-    echo "unix socket is currently not available" >&2
+    log_message "Unix socket is currently not available" >&2
     exit 1
   fi
   # Delayed startup
   if [ "$AUTOHEAL_START_PERIOD" -gt 0 ]
   then
-  echo "Monitoring containers for unhealthy status in $AUTOHEAL_START_PERIOD second(s)"
+    log_message "Monitoring containers for unhealthy status in $AUTOHEAL_START_PERIOD second(s)"
     sleep "$AUTOHEAL_START_PERIOD" &
     wait $!
   fi
 
+  log_message "Autoheal is running..."
   while true
   do
     STOP_TIMEOUT=".Labels[\"autoheal.stop.timeout\"] // $AUTOHEAL_DEFAULT_STOP_TIMEOUT"
@@ -151,19 +160,18 @@ then
     do
       # shellcheck disable=2039
       CONTAINER_SHORT_ID=${CONTAINER_ID:0:12}
-      DATE=$(date +%d-%m-%Y" "%H:%M:%S)
 
       if [ "$CONTAINER_NAME" = "null" ]
       then
-        echo "$DATE Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
+        log_message "Container name of (${CONTAINER_SHORT_ID}) is null, which implies container does not exist - don't restart" >&2
       elif [ "$CONTAINER_STATE" = "restarting" ]
       then
-        echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be restarting - don't restart"
+        log_message "Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be restarting - don't restart"
       else
-        echo "$DATE Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
+        log_message " Container $CONTAINER_NAME (${CONTAINER_SHORT_ID}) found to be unhealthy - Restarting container now with ${TIMEOUT}s timeout"
         if ! restart_container "$CONTAINER_ID" "$TIMEOUT"
         then
-          echo "$DATE Restarting container $CONTAINER_SHORT_ID failed" >&2
+          log_message "Restarting container $CONTAINER_SHORT_ID failed" >&2
           notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be unhealthy. Failed to restart the container!" &
         else
           notify_webhook "Container ${CONTAINER_NAME:1} (${CONTAINER_SHORT_ID}) found to be unhealthy. Successfully restarted the container!" &
@@ -174,7 +182,7 @@ then
     sleep "$AUTOHEAL_INTERVAL" &
     wait $!
   done
-
+  
 else
   exec "$@"
 fi
